# Travis CI (MIT License) configuration file for the solitude WordPress theme.
# @link https://travis-ci.org/
# if [[ "$SNIFF" == "1" ]];
#     - npm install -g jscs; fi
# - npm install -g jshint; fi
# - wget https://develop.svn.wordpress.org/trunk/.jshintrc; fi

language: php

notifications:
  on_success: never
  on_failure: change

php:
  - nightly
  - 7.1
  - 7.0

matrix:
    allow_failures:
    - php: nightly
    fast_finish: true

    include:
        - php: '7.1'
        - php: '7.0'

before_script:
    - composer wp-install

script:
    - vendor/bin/phpunit tests/basic_theme
