# Travis CI (MIT License) configuration file for the solitude WordPress theme.
# @link https://travis-ci.org/
# if [[ "$SNIFF" == "1" ]];
#     - npm install -g jscs; fi
# - npm install -g jshint; fi
# - wget https://develop.svn.wordpress.org/trunk/.jshintrc; fi

language: php

php:
  - nightly
  - 7.2

env:
  - WP_VERSION=master WP_MULTISITE=0

matrix:
    allow_failures:
    - php: nightly
    fast_finish: true

    include:
        - php: '7.2'

before_script:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - export WP_DEVELOP_DIR=/tmp/wordpress/
