# .circleci/config.yml

references:
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    passwords-evolved.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    passwords-evolved
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    tonyk

  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/passwords-evolved

  workspace_root: &workspace_root
    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  phpunit_job: &phpunit_job
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run PHP unit tests
          command: vendor/bin/phpunit test_basic_theme.php

jobs:
  test_php72:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.2

  test_php71:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.1

  test_php70:
    <<: *phpunit_job
    docker:
      - image: circleci/php:7.0

  test_php56:
    <<: *phpunit_job
    docker:
      - image: circleci/php:5.6

  test_php55:
    <<: *phpunit_job
    docker:
      - image: vandries/phpenv:5.5

  test_php54:
    <<: *phpunit_job
    docker:
      - image: vandries/phpenv:5.4
